#!/bin/sh
source $CMSSW_BASE/src/FlowCorrAna/DiHadronCorrelationAnalyzer/prod/setupfiles/setupfile_PAData_Trigger_5TeV
export TRIGGERNAMES="HLT_PAPixelTracks_Multiplicity100_v1 HLT_PAPixelTracks_Multiplicity130_v1 HLT_PAPixelTracks_Multiplicity160_v1 HLT_PAPixelTracks_Multiplicity190_v1 HLT_PAPixelTracks_Multiplicity100_v2 HLT_PAPixelTracks_Multiplicity130_v2 HLT_PAPixelTracks_Multiplicity160_v2 HLT_PAPixelTracks_Multiplicity190_v2"

export PTTRGMINARRAY="0.3"
export PTTRGMAXARRAY="3.0"
export PTASSMINARRAY="0.3"
export PTASSMAXARRAY="3.0"

#NMIN=(220 240)
#NMAX=(240 260)
NMIN=(220)
NMAX=(260)

export TRGID="TrackP"
export ASSID="TrackM"
