#!/bin/sh
source $CMSSW_BASE/src/FlowCorrAna/DiHadronCorrelationAnalyzer/prod/setupfiles/setupfile_PAData_Trigger_5TeV
export TRIGGERNAMES="HLT_PAPixelTracks_Multiplicity100_v1 HLT_PAPixelTracks_Multiplicity130_v1 HLT_PAPixelTracks_Multiplicity160_v1 HLT_PAPixelTracks_Multiplicity190_v1 HLT_PAPixelTracks_Multiplicity220_v1 HLT_PAPixelTracks_Multiplicity100_v2 HLT_PAPixelTracks_Multiplicity130_v2 HLT_PAPixelTracks_Multiplicity160_v2 HLT_PAPixelTracks_Multiplicity190_v2 HLT_PAPixelTracks_Multiplicity220_v2"

#export PTTRGMINARRAY="1.0"
#export PTTRGMAXARRAY="3.0"
#export PTASSMINARRAY="1.0"
#export PTASSMAXARRAY="3.0"

#export ZVTXBIN=120
#export ZVTXMIN=30
#export ZVTXMAX=150

#NMIN=(260 280)
#NMAX=(280 300)
NMIN=(260)
NMAX=(300)
