#!/bin/sh
source $CMSSW_BASE/src/FlowCorrAna/DiHadronCorrelationAnalyzer/prod/setupfiles/setupfile_PAData_Trigger_5TeV
export TRIGGERNAMES="HLT_PAPixelTracks_Multiplicity100_v1 HLT_PAPixelTracks_Multiplicity100_v2 HLT_PAPixelTracks_Multiplicity100_v3"

export ISCORR=0

export PTTRGMINARRAY="1.0"
export PTTRGMAXARRAY="2.0"
export PTASSMINARRAY="1.0"
export PTASSMAXARRAY="2.0"

NMIN=(100)
NMAX=(1000)
