#!/bin/sh
source $CMSSW_BASE/src/FlowCorrAna/DiHadronCorrelationAnalyzer/prod/setupfiles/setupfile_PAData_Trigger_5TeV
#export TRIGGERNAMES="HLT_PAPixelTracks_Multiplicity100_v1 HLT_PAPixelTracks_Multiplicity130_v1 HLT_PAPixelTracks_Multiplicity160_v1 HLT_PAPixelTracks_Multiplicity190_v1"

export PTTRGMINARRAY="0.3 0.5 1.0 1.5 2.0 2.5 3.0 4.0 5.0 6.0 8.0 10.0"
export PTTRGMAXARRAY="0.5 1.0 1.5 2.0 2.5 3.0 4.0 5.0 6.0 8.0 10.0 12.0"
export PTASSMINARRAY="0.3"
export PTASSMAXARRAY="3.0"

#NMIN=(0 5 10 20 30 40 50 60 80 100)
#NMAX=(5 10 20 30 40 50 60 80 100 120)
#NMIN=(0 20 50 80)
#NMAX=(20 50 80 120)
NMIN=(0)
NMAX=(35)
