#!/bin/sh
source $CMSSW_BASE/src/FlowCorrAna/DiHadronCorrelationAnalyzer/prod/setupfiles/setupfile_PAData_Trigger_5TeV

export TRIGGERNAMES="HLT_PAHFSumET100_v1  HLT_PAHFSumET100_v2  HLT_PAHFSumET100_v3"

NMIN=(-1)
NMAX=(-1)

CENTMIN=(7 8)
CENTMAX=(8 9)
