#!/bin/sh
source $CMSSW_BASE/src/FlowCorrAna/DiHadronCorrelationAnalyzer/prod/setupfiles/setupfile_BASE_HighMult
export EVENTTYPE="EPOSReco_Minbias_5TeV"
export FILESETNAME="file:$FILESETDIR/fileset_${EVENTTYPE}_${TAG}.txt"
#export EFFHISTNAME="/net/hisrv0001/home/davidlw/scratch1/DiHadronCorrelations/efficiency/TrackCorrections_HIJING_538_OFFICIAL_Mar24.root"
#export CENTFILENAME="/net/hisrv0001/home/davidlw/scratch1/DiHadronCorrelations/centrality/centralityfile_data_2011.root"
#export PILEUPDISTFUNCHISTNAME="/net/hisrv0001/home/davidlw/scratch1/DiHadronCorrelations/efficiency/pileup_distfunc_pPb.root"
#export CENTTABLENAME="HFtowers"

#export MASSTRG=1.11593
#export MASSASS=1.11593

#export CHECKSIGN=1
export ISDOEVENTSHAPE=0
export ISHIGENINFONTUPLE=1
export ISVTXSEL=1
export ZVTXCENTER=0.48
export YVTXCENTER=0.40
export XVTXCENTER=0.24
### for 2010 data
#export ZVTXCENTER=0.16
#export YVTXCENTER=0.029
#export XVTXCENTER=0.095
export ZVTXMIN=-150
export ZVTXMAX=150
export ZVTXBIN=300
export RHOMIN=0.0
export RHOMAX=2.0

export PTTRGMINARRAY="0.3"
export PTTRGMAXARRAY="100.0"
export PTASSMINARRAY="0.3"
export PTASSMAXARRAY="100.0"
#export PTTRGMINARRAY="0.1 1.0 2.0 4.0 6.0"
#export PTTRGMAXARRAY="1.0 2.0 4.0 6.0 12.0"
#export PTASSMINARRAY="0.1 1.0 2.0 4.0 6.0"
#export PTASSMAXARRAY="1.0 2.0 4.0 6.0 12.0"

#export PTTRGMINARRAY="12.0 14.0 16.0 19.2 24.0 28.8 35.2 48.0 60.8"
#export PTTRGMAXARRAY="14.0 16.0 19.2 24.0 28.8 35.2 48.0 60.8 100.0"
#export PTASSMINARRAY="0.3 0.5 1.0 2.0 3.0 4.0 6.0 8.0 12.0 14.0 16.0 19.2 24.0"
#export PTASSMAXARRAY="0.5 1.0 2.0 3.0 4.0 6.0 8.0 12.0 14.0 16.0 19.2 24.0 28.8"

#export PTTRGMINARRAY="0.1 0.5 1.0 1.5 2.0 2.5 3.0 4.0 5.0 6.0 8.0"
#export PTTRGMAXARRAY="0.5 1.0 1.5 2.0 2.5 3.0 4.0 5.0 6.0 8.0 12.0"
#export PTASSMINARRAY="0.1 0.5 1.0 1.5 2.0 2.5 3.0 4.0 5.0 6.0 8.0"
#export PTASSMAXARRAY="0.5 1.0 1.5 2.0 2.5 3.0 4.0 5.0 6.0 8.0 12.0"

#export PTTRGMINARRAY="0.1 1.0 2.0 3.0 4.0 5.0 6.0 8.0"
#export PTTRGMAXARRAY="1.0 2.0 3.0 4.0 5.0 6.0 8.0 12.0"
#export PTASSMINARRAY="0.1 1.0 2.0 3.0 4.0 5.0 6.0 8.0"
#export PTASSMAXARRAY="1.0 2.0 3.0 4.0 5.0 6.0 8.0 12.0"

export TRGTRACKCOLLECTION="generalTracks"
export ASSTRACKCOLLECTION="generalTracks"
export VERTEXCOLLECTION="offlinePrimaryVertices"

export ISCORR=1
export ISHI=0
export ISHARMONICS=0
export ISPTWEIGHTTRG=1
export ISPTWEIGHTASS=1
export ISTRKQUALITY=1
#export NVTXMAX=1

#export NETABINS=8
#export NPHIBINS=40
export ETATRGMIN=-5.0
export ETATRGMAX=-3.0
export ETAASSMIN=3.0
export ETAASSMAX=5.0

export ISFULLMATRIX=1

export TRGID="CaloTower"
export ASSID="CaloTower"
#export TRGID="Track"
#export ASSID="Track"

#NMIN=(110 120 150 185 220 260)
#NMAX=(120 150 185 220 260 300)
NMIN=(0 20 40 60 80)
NMAX=(20 40 60 80 120)

CENTMIN=(-1)
CENTMAX=(-1)
#CENTMIN=(20 24 28 32 36 37 38 39)
#CENTMAX=(24 28 32 36 37 38 39 40)

export BKGFACTOR=20
