#!/bin/sh
source $CMSSW_BASE/src/FlowCorrAna/DiHadronCorrelationAnalyzer/prod/setupfiles/setupfile_PAData_Trigger_5TeV
#export TRIGGERNAMES="HLT_PAPixelTracks_Multiplicity160_v1"

export ISCORR=0
export ISTRKQUALITY=1

export PTTRGMINARRAY="0.1"
export PTTRGMAXARRAY="10000.0"
export PTASSMINARRAY="0.1"
export PTASSMAXARRAY="10000.0"

#export ETATRGMIN=-2.0
#export ETATRGMAX=2.0
#export ETAASSMIN=-2.0
#export ETAASSMAX=2.0

NMIN=(0 5 10 20 30 40 50 60 80 100 120)
NMAX=(5 10 20 30 40 50 60 80 100 120 150)
