#!/bin/sh
source $CMSSW_BASE/src/FlowCorrAna/DiHadronCorrelationAnalyzer/prod/setupfiles/setupfile_PAData_Trigger_5TeV
export TRIGGERNAMES="HLT_PAPixelTracks_Multiplicity130_v1 HLT_PAPixelTracks_Multiplicity130_v2 HLT_PAPixelTracks_Multiplicity130_v3"
#export PILEUPDISTFUNCHISTNAME="/net/hisrv0001/home/davidlw/scratch1/DiHadronCorrelations/efficiency/pileup_distfunc_pPb_2sigma_mode1.root"

export ISCORR=0

export PTTRGMINARRAY="0.1"
export PTTRGMAXARRAY="0.2"
export PTASSMINARRAY="0.1"
export PTASSMAXARRAY="0.2"

NMIN=(185)
NMAX=(220)
