#!/bin/sh
source $CMSSW_BASE/src/FlowCorrAna/DiHadronCorrelationAnalyzer/prod/setupfiles/setupfile_BASE_HighMult
export EVENTTYPE="PythiaReco_Minbias_2760GeV"
export FILESETNAME="file:$FILESETDIR/fileset_${EVENTTYPE}_${TAG}.txt"
export EFFHISTNAME="NULL"

export ISGENMULT=1
export ISDOEVENTSHAPE=0
export ISHIGENINFONTUPLE=0
export ISVTXSEL=0
export ZVTXBIN=300

export PTTRGMINARRAY="120.0"
export PTTRGMAXARRAY="10000"
export PTASSMINARRAY="0"
export PTASSMAXARRAY="100.0"
export PTMULTMIN=0.4
export PTMULTMAX=10000.0

export ETATRGMIN=-1.0
export ETATRGMAX=1.0
export ETAASSMIN=-2.4
export ETAASSMAX=2.4

export TRGID="GenJet"
export ASSID="GenParticle"

export PDGID=3122

NMIN=(-1)
NMAX=(-1)
