#!/bin/sh
source $CMSSW_BASE/src/FlowCorrAna/DiHadronCorrelationAnalyzer/prod/setupfiles/setupfile_PAData_Trigger_5TeV
#export TRIGGERNAMES="HLT_PAPixelTracks_Multiplicity100_v1 HLT_PAPixelTracks_Multiplicity130_v1 HLT_PAPixelTracks_Multiplicity100_v2 HLT_PAPixelTracks_Multiplicity130_v2"
export EFFHISTNAME=""

export PTTRGMINARRAY="12.0"
export PTTRGMAXARRAY="1000.0"
export PTASSMINARRAY="1.0"
export PTASSMAXARRAY="3.0"

NMIN=(150)
NMAX=(1000)
