#!/bin/sh
source $CMSSW_BASE/src/FlowCorrAna/DiHadronCorrelationAnalyzer/prod/setupfiles/setupfile_PAData_Trigger_5TeV
#export TRIGGERNAMES="HLT_PAPixelTracks_Multiplicity100_v1 HLT_PAPixelTracks_Multiplicity130_v1 HLT_PAPixelTracks_Multiplicity160_v1 HLT_PAPixelTracks_Multiplicity190_v1"

#NMIN=(0 5 10 20 30 40 50 60 80 100)
#NMAX=(5 10 20 30 40 50 60 80 100 120)
NMIN=(-1)
NMAX=(-1)
#NMIN=(0 20 35 90 110)
#NMAX=(20 35 90 110 120)
