#!/bin/sh
source $CMSSW_BASE/src/FlowCorrAna/DiHadronCorrelationAnalyzer/prod/setupfiles/setupfile_PAData_Trigger_5TeV
export TRIGGERNAMES="HLT_PAPixelTracks_Multiplicity190_v1 HLT_PAPixelTracks_Multiplicity190_v2 HLT_PAPixelTracks_Multiplicity190_v3"

export ISCORR=0

export PTTRGMINARRAY="0.1"
export PTTRGMAXARRAY="0.2"
export PTASSMINARRAY="0.1"
export PTASSMAXARRAY="0.2"

NMIN=(-1)
NMAX=(-1)
