#!/bin/sh
source $CMSSW_BASE/src/FlowCorrAna/DiHadronCorrelationAnalyzer/prod/setupfiles/setupfile_PAData_Trigger_5TeV
export TRIGGERNAMES="HLT_PAPixelTracks_Multiplicity100_v1 HLT_PAPixelTracks_Multiplicity130_v1 HLT_PAPixelTracks_Multiplicity160_v1 HLT_PAPixelTracks_Multiplicity190_v1 HLT_PAPixelTracks_Multiplicity100_v2 HLT_PAPixelTracks_Multiplicity130_v2 HLT_PAPixelTracks_Multiplicity160_v2 HLT_PAPixelTracks_Multiplicity190_v2"

export PTTRGMINARRAY="1.0"
export PTTRGMAXARRAY="3.0"
export PTASSMINARRAY="1.0"
export PTASSMAXARRAY="3.0"

export TRGID="CaloTower"
export ASSID="Track"

export ETATRGMIN=3.0
export ETATRGMAX=5.0
export ETAASSMIN=-2.4
export ETAASSMAX=2.4

NMIN=(220)
NMAX=(260)
