#!/bin/sh
source $CMSSW_BASE/src/FlowCorrAna/DiHadronCorrelationAnalyzer/prod/setupfiles/setupfile_BASE_HighMult
export EVENTTYPE="HIData_Minbias_2760GeV"
export FILESETNAME="file:$FILESETDIR/fileset_${EVENTTYPE}_${TAG}.txt"
export EFFHISTNAME="/net/hisrv0001/home/davidlw/scratch1/DiHadronCorrelations/efficiency/trkEffNew2012_HI_hiGoodTightMerged_xsec_smoothv5true.root"
export CENTFILENAME="/net/hisrv0001/home/davidlw/scratch1/DiHadronCorrelations/centrality/centralityfile_data_2011.root"
export CENTTABLENAME="HFtowers"

#export CHECKSIGN=1
export ISDOEVENTSHAPE=0
export ISVTXSEL=1
export ZVTXCENTER=-0.54
export YVTXCENTER=0.037
export XVTXCENTER=0.077
### for 2010 data
#export ZVTXCENTER=0.16
#export YVTXCENTER=0.029
#export XVTXCENTER=0.095
export ZVTXMIN=-150
export ZVTXMAX=150
export ZVTXBIN=300
export RHOMIN=0.0
export RHOMAX=0.02

#export PTTRGMINARRAY="12.0 14.0 16.0 19.2 24.0 28.8 35.2 48.0 60.8"
#export PTTRGMAXARRAY="14.0 16.0 19.2 24.0 28.8 35.2 48.0 60.8 100.0"
#export PTASSMINARRAY="0.3 0.5 1.0 2.0 3.0 4.0 6.0 8.0 12.0 14.0 16.0 19.2 24.0"
#export PTASSMAXARRAY="0.5 1.0 2.0 3.0 4.0 6.0 8.0 12.0 14.0 16.0 19.2 24.0 28.8"

export PTTRGMINARRAY="1.0"
export PTTRGMAXARRAY="10000.0"
export PTASSMINARRAY="1.0"
export PTASSMAXARRAY="10000.0"

export TRGTRACKCOLLECTION="hiGoodTightTracks"
export ASSTRACKCOLLECTION="hiGoodTightTracks"
export VERTEXCOLLECTION="hiSelectedVertex"

#export ISCORR=0
export ISHI=1
export ISHARMONICS=1
export ISPTWEIGHT=0

#export NETABINS=8
#export NPHIBINS=40
export ETATRGMIN=-2.4
export ETATRGMAX=0.0
export ETAASSMIN=0.0
export ETAASSMAX=2.4

export ISFULLMATRIX=1

#export TRGID="CaloTower"
#export ASSID="CaloTower"
#export TRGID="Track"
#export ASSID="Track"

NMIN=(-1)
NMAX=(-1)

CENTMIN=(10)
CENTMAX=(12)

export BKGFACTOR=3
