#!/bin/sh
source $CMSSW_BASE/src/FlowCorrAna/DiHadronCorrelationAnalyzer/prod/setupfiles/setupfile_BASE_HighMult
export FILESETNAME="file:$FILESETDIR/fileset_${EVENTTYPE}_${TAG}.txt"
#export TRGHISTNAME="/net/hisrv0001/home/davidlw/scratch1/DiHadronCorrelations/efficiency/trgEff70New.root"
export EFFHISTNAME="/net/hisrv0001/home/davidlw/scratch1/DiHadronCorrelations/efficiency/trkEff_pp_highmult_42X_origin.root"
export PILEUPDISTFUNCHISTNAME="/net/hisrv0001/home/davidlw/scratch1/DiHadronCorrelations/efficiency/pileup_distfunc_5.root"

#export CHECKSIGN=1
#export ISTRACKNTUPLE=1
#export TRIGGERNAMES="HLT_PixelTracks_Multiplicity85"
#export ISDOEVENTSHAPE=1
#export ISLEADTRACK=1

export YVTXCENTER=0.0125
export XVTXCENTER=0.092
export ZVTXBIN=200
export ZVTXMIN=-100
export ZVTXMAX=100

export PTTRGMINARRAY="0.1 1.0 2.0 4.0 6.0"
export PTTRGMAXARRAY="1.0 2.0 4.0 6.0 12.0"
export PTASSMINARRAY="0.1 1.0 2.0 4.0 6.0"
export PTASSMAXARRAY="1.0 2.0 4.0 6.0 12.0"

export TRGTRACKCOLLECTION="selectTracks"
export ASSTRACKCOLLECTION="selectTracks"
#export TRACKCOLLECTION="generalTracks"
#export VERTEXCOLLECTION="bestVertex"
export VERTEXCOLLECTION="offlinePrimaryVertices"

#export ISCORR=0
#export ISHI=0

#export NVTXMAX=1
#export VTXSEPMIN=0.2
export ISFULLMATRIX=1

#export NPHIBINS=40
#export NETABINS=48
export ETATRGMIN=-2.4
export ETATRGMAX=2.4
export ETAASSMIN=-2.4
export ETAASSMAX=2.4

export TRGID="Track" 
export ASSID="Track"

NMIN=(90)
NMAX=(110)

export BKGFACTOR=20
