#!/bin/sh
source $CMSSW_BASE/src/FlowCorrAna/DiHadronCorrelationAnalyzer/prod/setupfiles/setupfile_BASE_HighMult
export EVENTTYPE="PPData_Minbias_2760GeV"
export FILESETNAME="file:$FILESETDIR/fileset_${EVENTTYPE}_${TAG}.txt"
#export TRGHISTNAME="/net/hisrv0001/home/davidlw/scratch1/DiHadronCorrelations/efficiency/trgEff_minbias.root"
#export EFFHISTNAME="/net/hisrv0001/home/davidlw/scratch1/DiHadronCorrelations/efficiency/trkEff_pp_all_42X_origin.root"
#export EFFHISTNAME="/net/hisrv0001/home/davidlw/scratch1/DiHadronCorrelations/efficiency/TrackCorrection_HIJINGmb_pTmax12_Feb19.root"
#export EFFHISTNAME="/net/hisrv0001/home/davidlw/scratch1/DiHadronCorrelations/efficiency/trkEff_pp_533p3_origin.root"
export EFFHISTNAME="/net/hisrv0001/home/davidlw/scratch1/DiHadronCorrelations/efficiency/TrackCorrections_HIJING_538_OFFICIAL_Mar24.root"
#export PILEUPDISTFUNCHISTNAME="/net/hisrv0001/home/davidlw/scratch1/DiHadronCorrelations/efficiency/pileup_distfunc_pPb_2sigma_mode1.root"

#export CENTFILENAME="/net/hisrv0001/home/davidlw/scratch1/DiHadronCorrelations/centrality/centralityfile_data_2011.root"
#export CENTTABLENAME="HFtowers"
#export CENTRALITYCOLLECTION="pACentrality"

#export CHECKSIGN=0
#export ISDOEVENTSHAPE=1
#export TRIGGERNAMES="HLT_PAPixelTracks_Multiplicity100_v1"

export ZVTXBIN=300
export ZVTXMIN=-150
export ZVTXMAX=150

#export PTTRGMINARRAY="1.0"
#export PTTRGMAXARRAY="3.0"
#export PTASSMINARRAY="1.0"
#export PTASSMAXARRAY="3.0"

#export PTTRGMINARRAY="0.1 1.0 2.0 4.0 6.0"
#export PTTRGMAXARRAY="1.0 2.0 4.0 6.0 12.0"
#export PTASSMINARRAY="0.1 1.0 2.0 4.0 6.0"
#export PTASSMAXARRAY="1.0 2.0 4.0 6.0 12.0"
#export PTTRGMINARRAY="0.1 1.0 2.0 3.0 4.0 5.0 6.0 8.0"
#export PTTRGMAXARRAY="1.0 2.0 3.0 4.0 5.0 6.0 8.0 12.0"
#export PTASSMINARRAY="0.1 1.0 2.0 3.0 4.0 5.0 6.0 8.0"
#export PTASSMAXARRAY="1.0 2.0 3.0 4.0 5.0 6.0 8.0 12.0"
#export PTTRGMINARRAY="0.1 0.5 1.0 1.5 2.0 2.5 3.0 4.0 5.0 6.0 8.0"
#export PTTRGMAXARRAY="0.5 1.0 1.5 2.0 2.5 3.0 4.0 5.0 6.0 8.0 12.0"
#export PTASSMINARRAY="0.1 0.5 1.0 1.5 2.0 2.5 3.0 4.0 5.0 6.0 8.0"
#export PTASSMAXARRAY="0.5 1.0 1.5 2.0 2.5 3.0 4.0 5.0 6.0 8.0 12.0"
#export PTTRGMINARRAY="0.3 0.5 1.0 1.5 2.0 2.5 3.0 4.0 5.0 6.0 8.0 10.0"
#export PTTRGMAXARRAY="0.5 1.0 1.5 2.0 2.5 3.0 4.0 5.0 6.0 8.0 10.0 12.0"
#export PTASSMINARRAY="0.3"
#export PTASSMAXARRAY="3.0"
# high pt corr
export PTTRGMINARRAY="12.0 14.0 16.0 19.2 24.0 28.8 35.2"
export PTTRGMAXARRAY="14.0 16.0 19.2 24.0 28.8 35.2 48.0"
export PTASSMINARRAY="0.3 0.5 1.0 2.0 3.0 4.0 6.0 8.0 12.0"
export PTASSMAXARRAY="0.5 1.0 2.0 3.0 4.0 6.0 8.0 12.0 14.0"

#export PTTRGMINARRAY="0.3"
#export PTTRGMAXARRAY="3.0"
#export PTASSMINARRAY="0.3"
#export PTASSMAXARRAY="3.0"

#export TRGTRACKCOLLECTION="selectTracks"
#export ASSTRACKCOLLECTION="selectTracks"
#export TRGTRACKCOLLECTION="generalTracks"
#export ASSTRACKCOLLECTION="generalTracks"
export VERTEXCOLLECTION="offlinePrimaryVertices"
#export VERTEXCOLLECTION="pixelVertices"

#export NETABINS=512
#export NPHIBINS=512
export ETATRGMIN=-2.4
export ETATRGMAX=2.4
export ETAASSMIN=-2.4
export ETAASSMAX=2.4
#export VTXSEPMIN=0.6
#export NVTXMAX=1
export ISFULLMATRIX=1
export ISTRKQUALITY=1

export ISCORR=1
#export ISTRACKNTUPLE=1
#export ISHI=0

export TRGID="Track"
export ASSID="Track"
