#!/bin/sh

currentdir=$PWD

#dataset=HIData_Minbias_2760GeV_HighPtTrack2011_pixeltracks
#dataset=PAData_Minbias_5TeV_TRIGGER100_Express
#datadir=/mnt/hadoop/cms/store/user/davidlw/store/caf/user/davidlw/PA2013_FlowCorr_Express_v2
#datadir=/mnt/hadoop/cms/store/user/tuos/HIMinBiasUPC/FlowppTracking_Skim_HIRun2011_HIMinBiasUPC-peripheral/*
#datadir=/mnt/hadoop/cms/store/user/davidlw/HIHighPt/PR2011_HighPtTrack12_pixeltracks_TRKANASKIM_official_v6/*
#datadir=/mnt/hadoop/cms/store/user/davidlw/MinBias_TuneZ2star_7TeV_pythia6_442p5_v1/NMult170/Skims

#dataset=HijingReco_Minbias_5TeV_MBpPb538
#datadir=/mnt/hadoop/cms/store/user/davidlw/HIJING_MB/Hijing_FlowCorr_MB_v1/*

#dataset=HIJINGGen_Minbias_5TeV_MBpPb
#datadir=/mnt/hadoop/cms/store/user/kjung/Gen_Only_Hijing/Kurt1

#dataset=HijingReco_Minbias_5TeV_PbPbPeriph
#datadir=/mnt/hadoop/cms/store/user/davidlw/Hijing_MB_Peripheral_v1/Hijing_MB_Peripheral_RECO_v1/*

#dataset=HydjetReco_Minbias_2760GeV_PeripheralNew
#datadir=/mnt/hadoop/cms/store/user/davidlw/HYDGET_PERIPH_batch*/*/*

#dataset=EPOSReco_Minbias_5TeV_MBNew
#datadir=/mnt/hadoop/cms/store/user/davidlw/EPOS_pPb5TeV_Skim

#dataset=PAData_Minbias_5TeV_MBPilotPUNew
#datadir=/mnt/hadoop/cms/store/user/davidlw/PAPhysics/PA2012_TRKANASKIM_MB_v10_PU/*

#dataset=PAData_Minbias_5TeV_Jet_PromptReco
#datadir=/mnt/hadoop/cms/store/user/davidlw/PAHighPt/PA2013_FlowCorr_PromptReco_Jet_Gplus_v2/*

dataset=PAData_Minbias_5TeV_HM_ReRecoNewFinalTower
datadir=/mnt/hadoop/cms/store/user/davidlw/PAHighPt/PA2013_FlowCorr_PromptReco_TrkHM_Gplus_Rereco_v15/*

#dataset=PAData_Minbias_5TeV_MB_ReRecoNewFinal
#datadir=/mnt/hadoop/cms/store/user/davidlw/PAMinBiasUPC/PA2013_FlowCorr_PromptReco_MB_Gplus_Rereco_v11/*

#dataset=PAData_Minbias_5TeV_HM_PromptRecoNewFinal_Reverse
#datadir=/mnt/hadoop/cms/store/user/davidlw/PAMinBiasUPC/PA2013_FlowCorr_PromptReco_MB_Gplus_Reverse_v12/*

#dataset=PAData_Minbias_5TeV_HM_PromptRecoNew_Reverse
#datadir=/mnt/hadoop/cms/store/user/davidlw/PAHighPt//*

#dataset=PAData_Minbias_5TeV_HM_Express_run210676-210759
#datadir=/mnt/hadoop/cms/store/user/davidlw/store/caf/user/davidlw/PA2013_FlowCorr_Express_run210676-210759_v3

#dataset=PAData_Minbias_5TeV_HM_PromptSkimNew
#datadir=/mnt/hadoop/cms/store/user/davidlw/PAHighPt/PA2013_FlowCorr_PromptSkim_PURej2Sigma_v3/*

#dataset=PPData_Minbias_2760GeV_HighPtTrk2013
#datadir=/mnt/hadoop/cms/store/user/davidlw/PPJet/PP2013_FlowCorr_PromptReco_HighPtTrk_Gplus_v1/*

#dataset=PythiaReco_Minbias_2760GeV_TuneZ2_Pt120
#datadir=/mnt/hadoop/cms/store/himc/HiWinter13/QCD_Pt_120_TuneZ2_2p76TeV_pythia6/GEN-SIM-RECO/STARTHI53_V26-v1/10000

#dataset=PythiaReco_Minbias_2760GeV_TuneZ2_MB
#datadir=/mnt/hadoop/cms/store/himc/HiWinter13/MinBias_TuneZ2_2760GeV_pythia6/GEN-SIM-RECO/STARTHI53_V26-v1/20000

#dataset=PPData_Minbias_7TeV_MINBIAS_2010B_Apr21ReReco
#dataset=PPData_Minbias_7TeV_TRIGGER85_2010B_Apr21ReReco
#dataset=PPData_Minbias_7TeV_TRIGGER70_2010B_Apr21ReReco
#dataset=PPData_Minbias_7TeV_TRIGGER100_2010B_Apr21ReReco
#dataset=PPData_Minbias_7TeV_MINBIAS_2010A_Apr21ReReco
#dataset=PPData_Minbias_7TeV_TRIGGER85_2010A_Apr21ReReco
#dataset=PPData_Minbias_7TeV_TRIGGER70_2010A_Apr21ReReco
#dataset=PPData_Minbias_7TeV_MINBIAS_C10_398p2

#datadir=/mnt/hadoop/cms/store/results/heavy-ions/MinimumBias/StoreResults-PP2010A_Apr21ReReco_TRKANASKIM_HIGHMULT_v2-d3b00b9920e9d4ebdfcff6a3f8ddc689-ppGoodColl_minbias/*/*/*/*
#datadir=/mnt/hadoop/cms/store/results/heavy-ions/MinimumBias/StoreResults-PP2010A_Apr21ReReco_TRKANASKIM_HIGHMULT_v2-d3b00b9920e9d4ebdfcff6a3f8ddc689-ppGoodColl_trigger70/*/*/*/*
#datadir=/mnt/hadoop/cms/store/results/heavy-ions/MinimumBias/StoreResults-PP2010A_Apr21ReReco_TRKANASKIM_HIGHMULT_v2-d3b00b9920e9d4ebdfcff6a3f8ddc689-ppGoodColl_trigger85/*/*/*/*
#datadir=/mnt/hadoop/cms/store/results/heavy-ions/MinimumBias/StoreResults-PP2010B_Apr21ReReco_TRKANASKIM_HIGHMULT_v2-d3b00b9920e9d4ebdfcff6a3f8ddc689-ppGoodColl_minbias/*/*/*/*
#datadir=/mnt/hadoop/cms/store/results/heavy-ions/MinimumBias/StoreResults-PP2010B_Apr21ReReco_TRKANASKIM_HIGHMULT_v2-d3b00b9920e9d4ebdfcff6a3f8ddc689-ppGoodColl_trigger100/*/*/*/*
#datadir=/mnt/hadoop/cms/store/results/heavy-ions/MinimumBias/StoreResults-PP2010B_Apr21ReReco_TRKANASKIM_HIGHMULT_v2-d3b00b9920e9d4ebdfcff6a3f8ddc689-ppGoodColl_trigger70/*/*/*/*
#datadir=/mnt/hadoop/cms/store/results/heavy-ions/MinimumBias/StoreResults-PP2010B_Apr21ReReco_TRKANASKIM_HIGHMULT_v2-d3b00b9920e9d4ebdfcff6a3f8ddc689-ppGoodColl_trigger85/*/*/*/*

mkdir -p filesets
#ls -l $datadir/*HM_*.root  | awk '{print "file:" $9}' > ./filesets/fileset_${dataset}.txt
ls -l $datadir/*.root  | awk '{print "file:" $9}' > ./filesets/fileset_${dataset}.txt
