#!/bin/sh

hostname | awk '{print "Running on " $1}'

dir=$CMSSW_BASE/src/FlowCorrAna/DiHadronCorrelationAnalyzer
cd $dir
dataset=$1
export TAG=$2
addition=$3
ffrom=$4
fto=$5
zvtxmin=$6
zvtxmax=$7
nmin=$8
nmax=$9
centmin=${10}
centmax=${11}

SETUPFILE_BASE="$dir/prod/setupfiles/setupfile_BASE"
SETUPFILE="$dir/prod/setupfiles/setupfile_$dataset"

source $SETUPFILE_BASE
source $SETUPFILE

echo "------------------------------------------------------------"
echo "SETUPFILE=$SETUPFILE"
echo "FILESETNAME=$FILESETNAME"
echo "------------------------------------------------------------"

export TAG="${TAG}_${addition}"

root.exe -b $dir/test/rootlogon.C <<EOF
.L $dir/test/RunEventPlaneAnalysisFWLite.C+
RunEventPlaneAnalysisFWLite(${ffrom},${fto},${zvtxmin},${zvtxmax},${nmin},${nmax},${centmin},${centmax});
.q
EOF
